// vocabulary.js — project-type-aware language layer
// Every creative discipline uses the same underlying data model.
// This module provides the correct words for each context.

export const VOCAB = {
  film: {
    node:       'Scene',
    nodes:      'Scenes',
    shot:       'Shot',
    shots:      'Shot list',
    act:        'Act',
    acts:       'Acts',
    zone:       'Zone',
    subject:    'Interview subject',
    subjects:   'Interview subjects',
    crew:       'Crew',
    brief:      'Creative brief',
    stage:      'Stage',
    wrap:       'Wrap document',
    callsheet:  'Call sheet',
    defaultActs: ['Act I', 'Act II', 'Act III'],
    nodeVerb:   'Add scene',
    nodeHint:   'Scene name — e.g. Opening Sequence',
    descHint:   'What is this scene trying to do? Describe the mood, the purpose, the creative direction…',
    shotPresets: ['Interview — ECU', 'B-roll — WS', 'Drama — MS', 'Archival', 'Graphic / Animation'],
  },
  brand: {
    node:       'Beat',
    nodes:      'Beats',
    shot:       'Shot',
    shots:      'Shot list',
    act:        'Chapter',
    acts:       'Chapters',
    zone:       'Zone',
    subject:    'Talent',
    subjects:   'Talent',
    crew:       'Team',
    brief:      'Brand brief',
    stage:      'Present',
    wrap:       'Wrap document',
    callsheet:  'Call sheet',
    defaultActs: ['Hook', 'Build', 'Resolution'],
    nodeVerb:   'Add beat',
    nodeHint:   'Beat name — e.g. The Problem',
    descHint:   'What does this beat need to communicate? What feeling should it leave?',
    shotPresets: ['Product — ECU', 'Lifestyle — WS', 'Talent — MS', 'Graphic / Motion'],
  },
  music: {
    node:       'Moment',
    nodes:      'Moments',
    shot:       'Shot',
    shots:      'Shot list',
    act:        'Section',
    acts:       'Sections',
    zone:       'Section',
    subject:    'Artist',
    subjects:   'Artists',
    crew:       'Crew',
    brief:      'Creative brief',
    stage:      'Playback',
    wrap:       'Wrap document',
    callsheet:  'Call sheet',
    defaultActs: ['Intro', 'Verse', 'Chorus', 'Bridge', 'Outro'],
    nodeVerb:   'Add moment',
    nodeHint:   'Moment name — e.g. Chorus — wide pull',
    descHint:   'What visual treatment fits this moment? What emotion does it need to carry?',
    shotPresets: ['Performance — ECU', 'Performance — WS', 'Crowd', 'Cutaway', 'B-roll'],
  },
  website: {
    node:       'Section',
    nodes:      'Sections',
    shot:       'Component',
    shots:      'Components',
    act:        'Page',
    acts:       'Pages',
    zone:       'Page',
    subject:    'Contributor',
    subjects:   'Contributors',
    crew:       'Team',
    brief:      'Project brief',
    stage:      'Present',
    wrap:       'Project document',
    callsheet:  'Content brief',
    defaultActs: ['Hero', 'Value', 'Features', 'CTA'],
    nodeVerb:   'Add section',
    nodeHint:   'Section name — e.g. Hero — main statement',
    descHint:   'What does this section communicate? What action should it drive?',
    shotPresets: ['Hero layout', 'Feature card', 'Testimonial', 'CTA block', 'Footer'],
  },
  deck: {
    node:       'Slide',
    nodes:      'Slides',
    shot:       'Detail',
    shots:      'Slide notes',
    act:        'Chapter',
    acts:       'Chapters',
    zone:       'Chapter',
    subject:    'Stakeholder',
    subjects:   'Stakeholders',
    crew:       'Team',
    brief:      'Pitch brief',
    stage:      'Present deck',
    wrap:       'Deck document',
    callsheet:  'Content brief',
    defaultActs: ['Problem', 'Solution', 'Market', 'Ask'],
    nodeVerb:   'Add slide',
    nodeHint:   'Slide name — e.g. The Problem',
    descHint:   'What argument does this slide make? What must the audience believe after seeing it?',
    shotPresets: ['Title slide', 'Data / chart', 'Quote', 'Visual', 'CTA'],
  },
  campaign: {
    node:       'Touchpoint',
    nodes:      'Touchpoints',
    shot:       'Asset',
    shots:      'Asset list',
    act:        'Phase',
    acts:       'Phases',
    zone:       'Phase',
    subject:    'Collaborator',
    subjects:   'Collaborators',
    crew:       'Team',
    brief:      'Campaign brief',
    stage:      'Present',
    wrap:       'Campaign document',
    callsheet:  'Production brief',
    defaultActs: ['Awareness', 'Consideration', 'Conversion'],
    nodeVerb:   'Add touchpoint',
    nodeHint:   'Touchpoint name — e.g. Launch social — Instagram',
    descHint:   'What does this touchpoint need to achieve? Who is seeing it and where?',
    shotPresets: ['Social — square', 'Social — story', 'OOH', 'Digital banner', 'Video ad'],
  },
  photo: {
    node:       'Shot',
    nodes:      'Shots',
    shot:       'Frame',
    shots:      'Frame list',
    act:        'Set',
    acts:       'Sets',
    zone:       'Set',
    subject:    'Subject',
    subjects:   'Subjects',
    crew:       'Crew',
    brief:      'Creative brief',
    stage:      'Proof',
    wrap:       'Project document',
    callsheet:  'Call sheet',
    defaultActs: ['Opening', 'Feature', 'Contextual'],
    nodeVerb:   'Add shot',
    nodeHint:   'Shot name — e.g. Portrait — studio window',
    descHint:   'What quality of light, mood, and composition are you after?',
    shotPresets: ['Portrait — tight', 'Portrait — environmental', 'Detail', 'Wide establishing'],
  },
  other: {
    node:       'Item',
    nodes:      'Items',
    shot:       'Detail',
    shots:      'Details',
    act:        'Phase',
    acts:       'Phases',
    zone:       'Phase',
    subject:    'Person',
    subjects:   'People',
    crew:       'Team',
    brief:      'Project brief',
    stage:      'Present',
    wrap:       'Project document',
    callsheet:  'Production brief',
    defaultActs: ['Phase 1', 'Phase 2', 'Phase 3'],
    nodeVerb:   'Add item',
    nodeHint:   'Item name',
    descHint:   'Describe this item — its purpose, scope, and intended outcome.',
    shotPresets: [],
  },
}

// Get vocabulary for a project type, falling back to film
export function getVocab(projectType) {
  return VOCAB[projectType] ?? VOCAB.film
}

// Shorthand for a single term
export function term(projectType, key) {
  return getVocab(projectType)[key] ?? VOCAB.film[key] ?? key
}
